name: Zip and Upload Static Website to S3

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip frontend directory
      run: |
        zip -r build.zip fronend

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exact-timestamps
      env:
        AWS_S3_BUCKET: dva-artifacts-bucket
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: .
        DEST_DIR: frontend/build/
