name: Zip and Upload build.zip to S3

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    


    - name: Zip frontend folder
      run: |
        zip -r build.zip frontend

    - name: Upload build.zip to S3
      run: |
        aws s3 cp build.zip s3://dva-artifacts-bucket/frontend/build/build.zip --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
